FROM node:24-slim

WORKDIR /app


RUN apt-get update -y && apt-get install -y openssl

RUN npm i -g pnpm@10.33.0


COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install --filter http-backend...
RUN pnpm run db:generate
RUN pnpm run build --filter http-backend... 

EXPOSE 3001

CMD [ "pnpm","run","start:backend" ]

