FROM node:24-alpine

WORKDIR /app

RUN npm i -g pnpm


COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install --filter http-backend...
RUN pnpm run db:generate

EXPOSE 3001

CMD [ "pnpm","run","start:backend" ]

