FROM node:24-alpine

WORKDIR /app

RUN npm i -g pnpm


COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN pnpm install --filter frontend...
RUN pnpm run db:generate

EXPOSE 3000

CMD [ "pnpm","run","start:frontend" ]