FROM node:24-alpine

WORKDIR /app

RUN npm i -g pnpm

# ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN pnpm install --filter frontend...

ARG NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_RAZORPAY_KEY
ENV NEXT_PUBLIC_RAZORPAY_KEY=$NEXT_PUBLIC_RAZORPAY_KEY


RUN  pnpm run build --filter frontend... 

EXPOSE 3000

CMD [ "pnpm","run","start:frontend" ]