FROM node:24-alpine

WORKDIR /app

RUN npm i -g pnpm

# ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN pnpm install --filter frontend...
# RUN pnpm run db:generate
# RUN DATABASE_URL=$DATABASE_URL pnpm run build --filter frontend... 
RUN  pnpm run build --filter frontend... 

EXPOSE 3000

CMD [ "pnpm","run","start:frontend" ]